### ISSUE TITLE
Improve documentation [tracking]

### ISSUE THREAD

**Issue by jakalkhalili** [jenkinsci/kubernetes-operator#157]
Few improvements needed for the new docs:

- [x] We already have a working website (https://jenkinsci.github.io/kubernetes-operator). It's time to remove the documentation folder and promote external documentation instead.

- [x] Some of the links on the website don't work, we'll fix them asap. (https://jenkinsci.github.io/docs/ vs https://jenkinsci.github.io/kubernetes-operator)

- [x] To help people contributing to the operator's documentation, we'll add a button that helps to edit documentation.

- [x] The icons/blurbs on the main page should lead to the specific parts of the docs that they are about (e.g. blurb about backup choud point to backup configuration docs)

- [x] Clarify headers for versions in the docs `0.1.1 -> 0.1.x`, `0.2.0 -> 0.2.x`

- [x] "Migration from v0.1.1" lacks information about secrets that now also need to be explicitly configured.

- [ ] Add missing content mentioned in `README.md`:
    - "handle graceful shutdown properly" - we need to add a "How it works" section that describes the whole jenkins lifecycle, esp. the shutdown mechanism for Jenkins, from the operator perspective and from k8s perspective
    - "orphaned jobs with no JNLP connection" - we need to add a "How it works" section that describes the JNLP connections and challenges with handling them in context of Kubernetes, and how operator handles it 

- [ ] Add section about LDAP https://github.com/jenkinsci/kubernetes-operator/issues/133

- [x] Add section about OpenShift https://github.com/jenkinsci/kubernetes-operator/issues/172

- [ ] Add sections about "challenges" with Multibranch plugin

- [x] Add a docs website generation target to the `Makefile`

- [ ] Update developer guide #247

- [ ] Use case of windows containers alongside linux containers #254

**Comment by jakalkhalili** [comment]
Some of the links on the website don't work, we'll fix them asap.

**Comment by jakalkhalili** [comment]
To help people contributing to the operator's documentation, we'll add a button that helps to edit documentation.

**Comment by pawelprazak** [comment]
The edit button should lead a path like this:
https://github.com/jenkinsci/kubernetes-operator/edit/master/website/content/en/docs/_index.md
but it 404's with this URL:
https://github.com/jenkinsci/kubernetes-operator/edit/master/content/docs/_index.md

**Comment by pawelprazak** [comment]
Instead of: 
![image](https://user-images.githubusercontent.com/48874/67491582-78cfc680-f675-11e9-84b0-3f9e50654962.png) 
it would be a lot better UX if it would be a button with a single word/action, like knative have: 
![image](https://user-images.githubusercontent.com/48874/67491698-9c930c80-f675-11e9-80e0-508118b0241f.png)
Just with our colors.

So from the left: Configure, Learn, Report
