### ISSUE TITLE
OpenShift Support [tracking]

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#190]
This a tracking issue for OpenShift support:
- [x] #166 - `JENKINS_HOME` as a overwrite-able env variable
- [x] #194 - Disable resources.limits and resources.requests default values if not set
- [x] #197 - Post Admission Controller validation
- [x] #199 - Generalize Jenkins container command validation
- [x] #200 - Allow for additional RBAC role bindings for Jenkins master
- [x] #201 - Fix issues with plugin installation in custom container images
- [x] #203 - Allow for the local dev mode to be used with various providers
- [x] #193 - Add ability to disable `CSRFProtection` in the Jenkins master

- [x] #170 - Issues regarding Jenkins startup on Openshift
- [x] #171 - Issue garding Jenkins startup on Openshift

- [x] #185 - Discussion : Container Level Validation
- [ ] #172 - Documentation for running the Jenkins Operator on Openshift
- [x] e2e tests for OpenShift

**Comment by tomaszsek** [comment]
Added in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.4.0
